- name: LoadRunner Cloud
  # You may pin to the exact commit or the version.
  # uses: MicroFocus/lrc-gh-action@e73d11dd1db08b1c8fbeab1d561ffd22f1ed134d
  uses: MicroFocus/lrc-gh-action@v1.0.6
  with:
    # LRC URL
    lrc_server: https://loadrunner-cloud.saas.microfocus.com # default is https://loadrunner-cloud.saas.microfocus.com
    # Tenant ID
    lrc_tenant: 300160516
    # Project ID
    lrc_project: 1 # default is 1
    # Test ID
    lrc_test_id: 1 # optional
    # The directory to save results
    lrc_output_dir: # optional, default is ./
    # Target report types. For example: pdf, docx, csv
    lrc_report_types: pdf # optional, default is 
