on: 
  workflow_dispatch:
    inputs:
      lrc_server:
        description: 'LRC URL'
        required: true
        default: 'https://loadrunner-cloud.saas.microfocus.com'
      lrc_tenant:
        description: 'Tenant ID'
        required: true
      lrc_project:
        description: 'Project ID'
        required: true
        default: '1'
      lrc_test_id:
        description: 'Test ID'
        required: true
