on:
 workflow_dispatch:
jobs:
  load_test:
    runs-on: self-hosted
    name: Start a load test
    steps:
      - name: Run test in LoadRunner Cloud
        uses: MicroFocus/lrc-gh-action@v1.0.6
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: 'oauth2-Yefr3WkfStbaEiFn79Vf@microfocus.com'
          LRC_CLIENT_SECRET: 'U3g17QRteI2o8gdTYKXP'
        with:
          lrc_server: 'https://loadrunner-cloud.saas.microfocus.com'
          lrc_tenant: '300160516'
          lrc_project: '1'
          lrc_test_id: '2'
